### ISSUE TITLE
Error report for version 0.8

### ISSUE THREAD

**Issue by rushairer** [thedevdojo/voyager-themes#11]
That is my first time of installing voyager-thems.
I found some errors.

1.
I use maria DB latest version. 
The index of `folder` varchar 255 is too long.
so I chang the code of vendor/voyager-themes/src/VoyagerThemesServiceProvider.php at line 179

``` php
$table->string('folder', 191)->unique();
```

2.
Then, it create the tables. well.

3.
But 

```

/var/www/webapp/vendor/voyager-themes/src/VoyagerThemesServiceProvider.php at line 154
   
$middleware_folder = $themes_folder . '/' . $theme->folder . '/middleware';

takes an error:

"Trying to get property of non-object"
```
so, I add that

```
if (empty($theme)) { 
  return;
}

under line 153.
```

**Comment by tnylea** [comment]
@rushairer This should be added into the latest version. Let me know if you see it in there.

Thanks for this :)

**Comment by rushairer** [comment]
@tnylea thanks.
