### ISSUE TITLE
'voyager.admin.routing' is a hard code

### ISSUE THREAD

**Issue by rushairer** [thedevdojo/voyager-themes#13]
voyager-themes/src/VoyagerThemesServiceProvider.php at line 36:

app(Dispatcher::class)->listen('voyager.admin.routing', function ($router) {

I think 'voyager.admin.routing' is a hard code.

If I want change the prefix of voyager at routes/web.php, it do not work.
I need make a new ServiceProvider for listen.

**Comment by marktopper** [comment]
`voyager.admin.routing` is an event, which is used to add new Voyager routes.

If you are using another slug for the admin panel, then make sure to update the `config/voyager.php` file and set `prefix` to whatever you are using.

Besides that you also have to update the `routes/web.php` file from:
```
Route::group(['prefix' => 'admin'], function () {
    Voyager::routes();
});
```
To use the correct prefix there as well.

**Comment by rushairer** [comment]
@marktopper thanks.

**Comment by farmanali000** [comment]
After starting of the installer of the voyager theme, it is noticeable that some new routings are added and the the file web.php which appears like that:

Route :: group (['prefix' => 'admin'], function () {
     Voyager :: routes ();
});
That is the reason why the theme voyage routes are rendered, but you can modify the prefix of admin if you will required or you can set any configuration route as per your demand, for example middleware or domain.
[1 dollar web hosting](http://blowhoster.com/)
