### ISSUE TITLE
Website crash on theme options

### ISSUE THREAD

**Issue by durancu** [thedevdojo/voyager-themes#14]
Once I installed and enabled theme, I tried to change options but website crashes with this error:

**Constant ACTIVE_THEME_FOLDER already defined (View: \/var\/app\/current\/vendor\/voyager-themes\/resources\/views\/options.blade.php**

Can be fixed replacing line 58, in voyager-themes/resources/views/options.blade.php with:

`<?php if (!defined("ACTIVE_THEME_FOLDER")) define("ACTIVE_THEME_FOLDER", $theme->folder); ?>`

**Comment by durancu** [comment]
Can be fixed replacing line 58, in voyager-themes/resources/views/options.blade.php with:

<?php if (!defined("ACTIVE_THEME_FOLDER")) define("ACTIVE_THEME_FOLDER", $theme->folder); ?>

**Comment by michaelbelow43** [comment]
I want to know that why is the WordPress syntax error happening by installing voyager theme?
[proxy site](https://www.safeproxysite.club/)
