### ISSUE TITLE
no migration

### ISSUE THREAD

**Issue by ibourgeois** [thedevdojo/voyager-themes#2]
installing this hook creates the following error: 

```
Illuminate \ Database \ QueryException (42S02)
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'velms.voyager_themes' doesn't exist (SQL: select * from `voyager_themes` where `active` = 1 limit 1)
```

**Comment by ibourgeois** [comment]
the update solved the issue. thanks!

**Comment by billoo2378** [comment]
Hello, I want to install the voyager theme in my site http://gems-band.net , but i had known from some sources that there is a migration of data issues occurs occaisionally, please comment
