### ISSUE TITLE
No theme options displayed after install

### ISSUE THREAD

**Issue by jeffochoa** [thedevdojo/voyager-themes#3]
Hi! could you please help me to set up this hook ?

I can't see any theme related options after install using `php artisan hook:install voyager-themes`

I also added the [sample-theme](https://github.com/thedevdojo/sample-theme) folder to `public`

I also tried to run `php artisan migrate` but I get `Nothing to migrate.`

**Comment by tnylea** [comment]
Hey @jeffochoa Did you add the sample-theme to `public\themes` folder? Let me know 👍 

Thanks!

**Comment by ato10** [comment]
Hi, same problem for me.
`Base table or view not found: 1146 Table 'voyager.voyager_theme_options' doesn't exist`

**Comment by jeffochoa** [comment]
@ato10 you need to add the service provider to `config/app.php` 

`VoyagerThemes\VoyagerThemesServiceProvider::class,`

**Comment by ato10** [comment]
thanks for reply.
now i cannot access to admin pages
`Symfony \ Component \ Debug \ Exception \ FatalThrowableError (E_ERROR)
Call to a member function connection() on null`

**Comment by jeffochoa** [comment]
@ato10 Make sure you are using the latest version. That issue was fixed here [https://github.com/thedevdojo/voyager-themes/pull/4](https://github.com/thedevdojo/voyager-themes/pull/4)

**Comment by ato10** [comment]
this is what my composer.json say
`"tcg/voyager": "^1.0",
"voyager-themes": "^0.3.0",`

**Comment by ato10** [comment]
using dev-master version it works great
Thanks

**Comment by jeffochoa** [comment]
Closing: fixed here #4
