### ISSUE TITLE
public vs resources

### ISSUE THREAD

**Issue by donatiss** [thedevdojo/voyager-themes#5]
Why we need to save theme blade files in public folder but not in resources?

**Comment by ibourgeois** [comment]
just submitted a pr for this.. #8

**Comment by ibourgeois** [comment]
i think that's about it... i cleaned it up quite a bit...

**Comment by donatiss** [comment]
i think it should be something like this:

-resources
--assets (for default assets)
--lang
--themes
---THEME_NAME
----views
----assets
--views (for default views)

**Comment by tnylea** [comment]
@tsulavi That's the way it is now in the latest version 👍 
This functionality has been added. So, resources is the default folder where the themes will live; however, this can be changed in the configuration file `config/themes.php` after you run `php artisan vendor:publish`

👍
